
version: 2

sources:
  - name: dvdrental_data
    description: "Data source for Dvtrental"
    database: dvdrental
    schema: dvdrental
    tables:
      - name: customer
        description: This table contains customers dat.
        columns:
          - name: customer_id
            description: Primary key for the customers
            tests:
              - unique
              - not_null
      - name: address
        description: "A starter dbt model"
        columns:
          - name: address_id
            description: "The primary key for this table"
            tests:
              - unique
              - not_null

      - name: payment
        description: "A starter dbt model"
        columns:
          - name: payment_id
            description: "The primary key for this table"
            tests:
              - unique
              - not_null

      - name: city
        description: "A starter dbt model"
        columns:
          - name: city_id
            description: "The primary key for this table"
            tests:
              - unique
              - not_null

      - name: country
        description: "A starter dbt model"
        columns:
          - name: country_id
            description: "The primary key for this table"
            tests:
              - unique
              - not_null
                
      - name: film
        description: "A starter dbt model"
        columns:
          - name: film_id
            description: "The primary key for this table"
            tests:
              - unique
              - not_null

      - name: inventory
        description: "A starter dbt model"
        columns:
          - name: inventory_id
            description: "The primary key for this table"
            tests:
              - unique
              - not_null

      - name: film_category 
        description: "A starter dbt model"
        columns:
            - name: category_id
              description: "The primary key for this table"
              tests:
                - unique
                - not_null
      
      - name: category 
        description: "A starter dbt model"
        columns:
            - name: category_id
              description: "The primary key for this table"
              tests:
                - unique
                - not_null
          
      - name: rental
        description: "A starter dbt model"
        columns:
          - name: rental_id
            description: "The primary key for this table"
            tests:
              - unique
              - not_null
      
      - name: actor
        description: "A starter dbt model"
        columns:
          - name: actor_id
            description: "The primary key for this table"
            tests:
              - unique
              - not_null

      - name: actor_info
        description: "A starter dbt model"
        columns:
          - name: actor_id
            description: "The primary key for this table"
            tests:
              - unique
              - not_null

      - name: film_actor
        description: "A starter dbt model"
        columns:
          - name: actor_id
            description: "The primary key for this table"
            tests:
              - unique
              - not_null

      - name: staff
        description: "A starter dbt model"
        columns:
          - name: staff_id
            description: "The primary key for this table"
            tests:
              - unique
              - not_null

      - name: store
        description: "A starter dbt model"
        columns:
          - name: store_id
            description: "The primary key for this table"
            tests:
              - unique
              - not_null

